### ISSUE TITLE
原图太大，如何处理？

### ISSUE THREAD

**Issue by vincent4j** [1sters/material_design_zh#57]
在 google 原始页面中的图片都是 xhdpi 尺寸的，超级大；那如何变小呢？

原始图片链接如：
http://material-design.storage.googleapis.com/images/components-switches-checkbox-switches_07a_large_xhdpi.png

操作：
将最后的 xhdpi 改成 mdpi，形如：
http://material-design.storage.googleapis.com/images/components-switches-checkbox-switches_07b_large_mdpi.png

也就是说，google 服务器上存放了多套尺寸的图片。

**Comment by isnofate** [comment]
发现现在的图片路径里加了hash, 没办法通过改链接的方式找mdpi的图片了, 例如:

http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7SE1HYTloZG5mNUE/patterns_errors_userinput1.png

直接传原图还是用工具缩放下?

**Comment by awong1900** [comment]
现在是个什么做法？
