### ISSUE TITLE
如何添加视频

### ISSUE THREAD

**Issue by vincent4j** [1sters/material_design_zh#90]
1、在原始文章中找到视频的原始地址
- 鼠标右键视频
- 选择「复制视频网址」

例如「[Authentic Motion](http://www.google.com/design/spec/animation/authentic-motion.html#authentic-motion-mass-weight)」章节的第一个视频地址为：
http://material-design.storage.googleapis.com/videos/animation-authentic-motion-authenticMotion_massAndWeight_ex1_large_xhdpi.webm

2、修成改「七牛」对应的地址
因为 google 服务器过慢，所以将所有的视频都传到「七牛」，只需将前面的「域名」更换即可。
由 
http://material-design.storage.googleapis.com
换成
http://materialdesign.qiniudn.com

最终地址为：
http://materialdesign.qiniudn.com/videos/animation-authentic-motion-authenticMotion_massAndWeight_ex1_large_xhdpi.webm

3、查看网页源码，找到 width 和 height
- 在浏览器中查看「[Authentic Motion](http://www.google.com/design/spec/animation/authentic-motion.html#authentic-motion-mass-weight)」章节源码  
- 在源码中检索视频文件名「animation-authentic-motion-authenticMotion_massAndWeight_ex1_large_xhdpi.webm」  
- 检索结果中，「video」标签下的「width」和「height」就是所要找的值  

4、往翻译稿中添加代码
假定上一步中查找的值为：width="740" height="270"

```
<video crossorigin="anonymous"  loop  controls width="740" height="270">
<source src="http://materialdesign.qiniudn.com/videos/animation-authentic-motion-authenticMotion_massAndWeight_ex1_large_xhdpi.webm" type="video/webm">
</video>
```

其中，仅以下三个值需要指定，其他保持不变：
- width
- height
- src

**Comment by awong1900** [comment]
视频是谁传到七牛上？

**Comment by vincent4j** [comment]
@awong1900 今天就会上传

**Comment by floydzhang315** [comment]
新增课程的video已上传至七牛上，请按照4j提供的操作流程来填充视频
